### ISSUE TITLE
Fix not applied to constructible objects menu

### ISSUE THREAD

**Issue by Meryl** [SkyHorizon3/SSE-Widescreen-Scale-Removed#1]
Using Untarnished UI and C.O.C.K.S. still left me with some squished interfaces, specifically the ones touched by C.O.C.K.S (for reference, [some screenshots](https://imgur.com/a/NTgimqk)). Based on [this file](https://github.com/SkyHorizon3/SSE-Widescreen-Scale-Removed/blob/main/src/Hooks.cpp), I think maybe the plugin isn't applying its fix to the interface C.O.C.K.S. touches. This is somewhat of a blind guess, because I am not familiar enough with the inner workings of any of the involved mods to know for sure, but considering WSR is supposed to fix the squishing effect I'd figure I report it.

**Comment by SkyHorizon3** [comment]
Thanks for reporting! I fixed this issue in the next version
